server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: portal-service
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: /db/changelog/db.changelog-master.xml
  security:
    oauth2:
      client:
        registration:
          keycloak:
            authorization-grant-type: authorization_code
            scope: openid
  mail:
    user: federico.chizhara@yandex.ru
    smtp:
      host: smtp.yandex.ru
      port: 465
      ssl:
        enable: true
      auth: true
  kafka:
    bootstrap-servers: localhost:29092
    topic:
      driver:
        name: portal.driver.info
      transport:
        name: portal.transport.info

keycloak:
  server-url: http://localhost:8080
  realm: gvinc

dadata:
  base-url: http://suggestions.dadata.ru
  company-get-path: http://suggestions.dadata.ru/suggestions/api/4_1/rs/findById/party

