spring:
  application:
    name: portal-service
  jpa:
    hibernate:
      ddl-auto: none
  security:
    oauth2:
      client:
        registration:
          keycloak:
            authorization-grant-type: authorization_code
            scope: openid
  mail:
    user: federico.chizhara@yandex.ru
    smtp:
      host: smtp.yandex.ru
      port: 465
      ssl:
        enable: true
      auth: true


server:
  port: 8082

keycloak:
  server-url: http://localhost:8080
  realm: gvinc

dadata:
  base-url: http://suggestions.dadata.ru
  company-get-path: http://suggestions.dadata.ru/suggestions/api/4_1/rs/findById/party